package de.dailab.recommender.graph.unirelationaldatasets;

import java.io.IOException;

import de.dailab.recommender.dataset.EntityType;
import de.dailab.recommender.dataset.MetadataName;
import de.dailab.recommender.dataset.RelationshipType;
import de.dailab.recommender.graph.UnirelationalGraphStoreDataset;
import de.dailab.recommender.text.TextSyntaxException;

/**
 * Access to the unirelational advogato dataset in the Graph Store.
 * 
 * @author autogenerated
 */
@SuppressWarnings("all")
public class AdvogatoDataset
      extends UnirelationalGraphStoreDataset
{
	/**
	 * Load the unirelational advogato dataset from the Graph Store.
	 * 
	 * @throws IOException on IO errors
	 * @throws TextSyntaxException syntax error in the text file
	 */
	public AdvogatoDataset()
	        throws IOException, TextSyntaxException
	{
		super("advogato");		
	}

	/**
	 * The name of the underlying dataset.  
	 */
	public final static String NAME = "advogato"; 

	/**
	 * The developer entity type. 
	 */
	public final static EntityType DEVELOPER = new EntityType("developer");

	/**
	 * The certificate relationship type. 
	 */
	public final static RelationshipType CERTIFICATE = new RelationshipType("certificate");
}	
