package de.dailab.recommender.graph.unirelationaldatasets;

import java.io.IOException;

import de.dailab.recommender.dataset.EntityType;
import de.dailab.recommender.dataset.MetadataName;
import de.dailab.recommender.dataset.RelationshipType;
import de.dailab.recommender.graph.UnirelationalGraphStoreDataset;
import de.dailab.recommender.text.TextSyntaxException;

/**
 * Access to the unirelational bibsonomy-2ui dataset in the Graph Store.
 * 
 * @author autogenerated
 */
@SuppressWarnings("all")
public class Bibsonomy2uiDataset
      extends UnirelationalGraphStoreDataset
{
	/**
	 * Load the unirelational bibsonomy-2ui dataset from the Graph Store.
	 * 
	 * @throws IOException on IO errors
	 * @throws TextSyntaxException syntax error in the text file
	 */
	public Bibsonomy2uiDataset()
	        throws IOException, TextSyntaxException
	{
		super("bibsonomy-2ui");		
	}

	/**
	 * The name of the underlying dataset.  
	 */
	public final static String NAME = "bibsonomy-2ui"; 
}	
