package de.dailab.recommender.graph.unirelationaldatasets;

import java.io.IOException;

import de.dailab.recommender.dataset.EntityType;
import de.dailab.recommender.dataset.MetadataName;
import de.dailab.recommender.dataset.RelationshipType;
import de.dailab.recommender.graph.UnirelationalGraphStoreDataset;
import de.dailab.recommender.text.TextSyntaxException;

/**
 * Access to the unirelational btc_aggregate dataset in the Graph Store.
 * 
 * @author autogenerated
 */
@SuppressWarnings("all")
public class BtcAggregateDataset
      extends UnirelationalGraphStoreDataset
{
	/**
	 * Load the unirelational btc_aggregate dataset from the Graph Store.
	 * 
	 * @throws IOException on IO errors
	 * @throws TextSyntaxException syntax error in the text file
	 */
	public BtcAggregateDataset()
	        throws IOException, TextSyntaxException
	{
		super("btc_aggregate");		
	}

	/**
	 * The name of the underlying dataset.  
	 */
	public final static String NAME = "btc_aggregate"; 

	/**
	 * The entity entity type. 
	 */
	public final static EntityType ENTITY = new EntityType("entity");
}	
