package de.dailab.recommender.graph.unirelationaldatasets;

import java.io.IOException;

import de.dailab.recommender.dataset.EntityType;
import de.dailab.recommender.dataset.MetadataName;
import de.dailab.recommender.dataset.RelationshipType;
import de.dailab.recommender.graph.UnirelationalGraphStoreDataset;
import de.dailab.recommender.text.TextSyntaxException;

/**
 * Access to the unirelational netflix dataset in the Graph Store.
 * 
 * @author autogenerated
 */
@SuppressWarnings("all")
public class NetflixDataset
      extends UnirelationalGraphStoreDataset
{
	/**
	 * Load the unirelational netflix dataset from the Graph Store.
	 * 
	 * @throws IOException on IO errors
	 * @throws TextSyntaxException syntax error in the text file
	 */
	public NetflixDataset()
	        throws IOException, TextSyntaxException
	{
		super("netflix");		
	}

	/**
	 * The name of the underlying dataset.  
	 */
	public final static String NAME = "netflix"; 

	/**
	 * The item entity type. 
	 */
	public final static EntityType ITEM = new EntityType("item");

	/**
	 * The user entity type. 
	 */
	public final static EntityType USER = new EntityType("user");
}	
